### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by kou** [mroonga/wordpress-mroonga#3]
TODO

  * [x] Confirm that wordpress-mroonga works well on WordPress on KUSANAGI
  * [x] Release to wordpress.org

**Comment by komainu8** [comment]
現在のMasterのプラグインがKUSANAGI上で正常に動作するかを確認しました。
以下にその手順と結果を記載します。

## 動作確認手順
### WordPress Mroonga プラグインのインストール

/home/kusanagi/プロファイル名/DocumentRoot/wp-content/plugins 配下に mroonga ディレクトリを作成します。
```
% mkdir /home/kusanagi/プロファイル名/DocumentRoot/wp-content/plugins/mroonga
```

作成したmroongaディレクトリにMroongaプラグインのファイル(mroonga.php)をアップロードします。
```
% scp ./mroonga.php root@IP Address:/home/kusanagi/プロファイル名/DocumentRoot/wp-content/plugins/mroonga/
```

### プラグインの有効化

サーバー上で以下のコマンドを実行し、Mroongaプラグインを有効化します。
```
% wp plugin activate mroonga
```

有効になったかどうかは以下のコマンドで確認します。
```
% wp plugin status

6 installed plugins:
  I akismet               4.0.2
  I hello                 1.6
  A mroonga               0.1.1
  I wp-multibyte-patch    2.8.1
  M kusanagi-wp-configure 0.7
  M wp-kusanagi           1.0.24
```
プラグイン名の前に記載されている アルファベットが `A`になっていれば、そのプラグインは有効になっています。

### 動作確認

サイトの検索窓からキーワードを入力して全文検索を行います。
検索結果がキーワードの出現頻度順になっていれば、プラグインは正常に動作していると判断します。

#### テストデータ
```
Posts

Posted on 2018年2月7日Edit "天気2"
天気2

くもり
あめ
はれ晴れ晴れ

Posted on 2018年2月6日Edit "天気1"
天気1

はれ
あめあめあめ
晴れ晴れ晴れ晴れ晴れ晴れ晴れ

Posted on 2018年2月5日Edit "天気"
天気

晴れ晴れ晴れはれ。
あめ
```

Mroongaのプラグインが有効では無い場合は、時系列順に検索結果が表示されます。

したがって、例えば、検索キーワードを`晴れ`として検索すると、プラグインが無効な場合は、`天気2`、`天気1`、`天気`の順で検索結果が表示されます。
プラグインが有効な場合は、キーワードの出現頻度順に表示されるので、`天気1`、`天気`、`天気2`の順で検索結果が表示されます。

### 動作確認結果

検索キーワードを`晴れ`として検索した結果を以下に記載します。

#### プラグイン有効時の検索結果
```
Search Results for: 晴れ
Posted on 2018年2月6日Edit "天気1"	
天気1

はれ あめあめあめ 晴れ晴れ晴れ晴れ晴れ晴れ晴れ

Posted on 2018年2月5日Edit "天気"	
天気

晴れ晴れ晴れはれ。 あめ

Posted on 2018年2月7日Edit "天気2"	
天気2

くもり あめ はれ晴れ晴れ
```

#### プラグイン無効時の検索結果
```
Search Results for: 晴れ
Posted on 2018年2月7日Edit "天気2"	
天気2

くもり あめ はれ晴れ晴れ2/6の投稿の`天気1`

Posted on 2018年2月6日Edit "天気1"	
天気1

はれ あめあめあめ 晴れ晴れ晴れ晴れ晴れ晴れ晴れ

Posted on 2018年2月5日Edit "天気"	
天気

晴れ晴れ晴れはれ。 あめ
```

上記結果の通り、プラグイン無効時は、検索キーワードの出現頻度順にかかわらず、時系列順に結果が表示されています。
(2/7の投稿の`天気2`→2/6の投稿の`天気1`→2/5の投稿の`天気`の順で結果が表示されています。)

プラグイン有効時は、時系列ではなく、検索キーワードが最も多く出現している `2/6の投稿の天気1` 次に検索キーワードが多く出現している `2/5の投稿の天気`、検索キーワードが最も出現しない`2/7の投稿の天気2`の順で結果が表示されています。

上記より、現在のMasterのプラグインはKUSANAGI上で正常に動作しています。

**Comment by komainu8** [comment]
(参考)
以下のコマンドでも、プラグインのインストールと有効化を行うことができますが、インストールするパッケージは、`https://downloads.wordpress.org/plugin/mroonga.zip`から取得するので、Masterのソースを動作確認するのには使えません。
```
wp plugin install Mroonga --activate
```

**Comment by kou** [comment]
リリースしました。

↓でも大丈夫になったか確認することってできます？

```console
% wp plugin install Mroonga --activate
```

**Comment by komainu8** [comment]
はい。可能ですので、以下のコマンドを実行して結果を報告します。

```
% wp plugin install Mroonga --activate
```

**Comment by kou** [comment]
あざっす。
問題がなかったらクローズしてください。

**Comment by komainu8** [comment]
以下のコマンドを実行して、0.1.1がインストールできるか確認しました。
```
% wp plugin install Mroonga --activate
```
上記のコマンドだと、インストールされますが、プラグインの有効化で失敗しました。
(インストール後の`% wp plugin status`の結果で`mroonga`の先頭のアルファベットが`A`になっていないので、インストールはされたが、有効になっていない状態です。)
```
[root@kusanagi71 plugins]# wp plugin status
5 installed plugins:
  I akismet               4.0.2
  I hello                 1.6
  I wp-multibyte-patch    2.8.1
  M kusanagi-wp-configure 0.7
  M wp-kusanagi           1.0.24

Legend: I = Inactive, M = Must Use

[root@kusanagi71 plugins]# wp plugin install Mroonga --activate
Installing Mroonga (0.1.1)
Downloading installation package from https://downloads.wordpress.org/plugin/mroonga.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'Mroonga'...
Warning: The 'Mroonga' plugin could not be found.
Success: Installed 1 of 1 plugins.

[root@kusanagi71 plugins]# wp plugin status
6 installed plugins:
  I akismet               4.0.2
  I hello                 1.6
  I mroonga               0.1.1
  I wp-multibyte-patch    2.8.1
  M kusanagi-wp-configure 0.7
  M wp-kusanagi           1.0.24

Legend: I = Inactive, M = Must Use
```

install に指定するプラグイン名(`Mroonga`)と`% wp plugin status`の結果で表示されるプラグイン名(`mroonga`)が異なるからでは無いかと考え、以下の通りコマンドを変更して実行したところ、インストールと有効化が出来ました。
```
% wp plugin install mroonga --activate
```

```
[root@kusanagi71 plugins]# wp plugin install mroonga --activate
Installing Mroonga (0.1.1)
Downloading installation package from https://downloads.wordpress.org/plugin/mroonga.zip...
Using cached file '/home/kusanagi/.wp-cli/cache/plugin/mroonga-0.1.1.zip'...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'mroonga'...
Plugin 'mroonga' activated.
Success: Installed 1 of 1 plugins.

[root@kusanagi71 plugins]# wp plugin status
6 installed plugins:
  I akismet               4.0.2
  I hello                 1.6
  A mroonga               0.1.1
  I wp-multibyte-patch    2.8.1
  M kusanagi-wp-configure 0.7
  M wp-kusanagi           1.0.24

Legend: I = Inactive, A = Active, M = Must Use
```

有効化後のサイトの検索結果は、キーワードの出現頻度順にソートされていましたので、`https://downloads.wordpress.org/plugin/mroonga.zip`からのインストールでも正常に動作します。

**Comment by kou** [comment]
動作確認に使ったWordPressのバージョンってわかります？
もし、readme.txtに書いているやつよりも新しかったら更新しておいてください。

**Comment by komainu8** [comment]
動作確認に使ったWordPressは4.9.2だったので、readme.txtを更新しておきました。
